# Generated by Django 4.2.8 on 2024-05-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_alter_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='map_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
