# Generated by Django 4.2.8 on 2024-06-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0011_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
