# Generated by Django 4.2.8 on 2024-06-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0012_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
